intro= "This is a glossary of terms. Users will be able to search any term of their choice and if the terms exists, the term and definition will be displayed and if not, it will tell the user that terms does not exists. "

usage= "The user is required to enter the term and when he/she clicks enter, the definition will display. \n To get the list of all available terms, enter: Full Terms, to generate the whole glossary, enter: Full Glossary."

dictionary={"Absolute Advantage":"Absolute advantage is the ability of an individual, company, region, or country to produce a greater quantity of a good or service with the same quantity of inputs per unit of time, or to produce the same quantity of a good or service per unit of time using a lesser quantity of inputs, than another entity that produces the same good or service.",
"Angel Investor":"An angel investor (also known as a private investor, seed investor or angel funder) is a high-net-worth individual who provides financial backing for small startups or entrepreneurs, typically in exchange for ownership equity in the company",
"Annual Percentage Rate":"Annual percentage rate (APR) refers to the yearly interest generated by a sum that's charged to borrowers or paid to investors.",
"Assets Under Management":"Assets under management (AUM) is the total market value of the investments that a person or entity manages on behalf of clients. Assets under management definitions and formulas vary by company.",
"Asset Management":"Asset management is the direction of all or part of a client's portfolio by a financial services institution, usually an investment bank, or an individual.",
"Balance Sheet":"A balance sheet is a financial statement that reports a company's assets, liabilities and shareholders' equity at a specific point in time, and provides a basis for computing rates of return and evaluating its capital structure."}

def searchTerm():
    term=input("Enter term \n")

    if term == "Full Terms":
        i=0
        for x in dictionary:
            i+=1
            print(f"{i} {x}", "\n")

    elif term == "Full Glossary":
        j=0
        for x in dictionary:
            j+=1
            print(f"{j} {dictionary[x]}", "\n")
             
    elif term in dictionary:
        print(dictionary[str(term)])

    elif term not in dictionary:
        print("Term not in dictionary, please search for a different term")
        searchTerm()
    print("Search for another term")
    searchTerm()
    


print(intro)
print(usage)
searchTerm()